version: "3"

services:

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - network


  imagedb:
    image: 'imagedb'
    build: ./Database/imagedb/
    container_name: imagedb
    ports: ["5000"]
    networks:
      - network
    volumes:
      - image_data:/var/lib/images:rw


  textdb:
    image: 'textdb'
    build: ./Database/textdb/
    container_name: textdb
    ports: ["5000"]
    networks:
      - network
    volumes:
      - text_data:/var/lib/text:rw


  dispatch:
    image: 'dispatch'
    container_name: dispatcher
    build: ./Dispatcher/
    ports:
      - "5000:5000"
    networks:
      - network
    restart: on-failure
    depends_on:
      - imagedb
      - rabbitmq

  reader:
    image: 'reader'
    container_name: reader
    build: ./Reader/
    ports:
      - "5001:5001"
    networks:
      - network
    restart: on-failure
    depends_on:
      - imagedb
    volumes:
      - image_data:/var/lib/images:rw

  object_detection:
    image: 'obj-detection'
    container_name: obj_detection
    build: ./MachineLearning/object_detection
    restart: on-failure
    networks:
      - network
    depends_on:
      - imagedb
      - rabbitmq
    volumes:
      - image_data:/var/lib/images:rw



  facial_detection:
    image: 'face-detection'
    container_name: face_detection
    build: ./MachineLearning/facial_detection
    restart: on-failure
    networks:
      - network
    depends_on:
      - imagedb
      - rabbitmq
    volumes:
      - image_data:/var/lib/images:rw



  nude_detection:
    image: 'nude-detection'
    container_name: nude_detection
    build: ./MachineLearning/nude_detection
    restart: on-failure
    networks:
      - network
    depends_on:
      - imagedb
      - rabbitmq
    volumes:
      - image_data:/var/lib/images:rw


  toxic_comments:
    image: 'toxic_comments'
    container_name: toxic_comments
    build: ./MachineLearning/toxic_comments
    restart: on-failure
    networks:
      - network
    depends_on:
      - textdb
      - rabbitmq
    volumes:
      - text_data:/var/lib/text:rw


networks:
  network: {}


volumes:
  image_data:
  text_data:


# powered by bee
